title: Minsoo Song
description: Minsoo Song's academic homepage
url: "https://ecoses042.github.io"
baseurl: ""

markdown: kramdown

sass:
    style: compressed
    sass_dir: _sass

nav:
  - name: "CV"
    link: "/Minsoo_Song_CV.pdf"
  - name: "NLP LAB"
    link: "https://sites.google.com/view/ssu-nlp/home"

footer: false
footer_url: "https://github.com/ankitsultana/researcher"
footer_text: "Page design by Ankit Sultana"
